# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gardener}
  s.version = "1.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bob Larrick"]
  s.date = %q{2011-02-09}
  s.description = %q{A Ruby on Rails Plugin to help you create seed data.  Useful when you want to move just a few pieces of data 		from one environment to another.  To my knowledge there is no other gem that will help you move a few records from your development or staging 		environment to your production environment.}
  s.email = %q{larrick@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "lib/gardener.rb"
  ]
  s.homepage = %q{https://github.com/deathbob/Gardener}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simple Seed Data Creation for Ruby on Rails.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

